### ISSUE TITLE
Authtoken cookie is always session expired

### ISSUE THREAD

**Issue by Mnosek** [StarcounterPrefabs/SignIn#40]
Basically the 'Remember me' checkbox doesn't work. I've investigated it a bit. It seems like on the server side there is a valid cookie expiration date set, but it has no effect in the browser. In result user is always logged out just after session ends up.

**Comment by warpech** [comment]
This is 100% reproducible when I have a breakpoint in SignIn app and 0% reproducible if I don't have a breakpoint.

@alemoi, does Starcounter have any timeout for a HTTP GET request that cancels the request after 10-11 seconds?

See the following screenshot:

![2016-08-30 17_01_51-launcher](https://cloud.githubusercontent.com/assets/566463/18094438/bdb154a8-6ed3-11e6-8381-a89ec9d84280.png)

**Comment by Mnosek** [comment]
At my machine it doesn't matter if I have breakpoints/debugger attached or not. Cookie is always session expired. Is it possible that this problem occurs only at pnext?

**Comment by warpech** [comment]
Note that similar symptoms happen if SignIn is started before Launcher (this is being fixed in https://github.com/Starcounter/Starcounter/issues/3800 and https://github.com/Starcounter/Starcounter/issues/3810)

Can you try again, but make sure Launcher is started before SignIn.

**Comment by Mnosek** [comment]
I've tried again (starting order):
- Starcounter 2.3.3771
- Launcher (Sweoffshore Portal)
- SignIn from master
- UserAdmin from master

Problem still occurs. Should I try with current Launcher version?

**Comment by warpech** [comment]
Actually I have a reverse problem - "Remember me" always remembers, even if it is unchecked. Investigating.

**Comment by warpech** [comment]
Some problems that I've found: 

1. Session cookie uses wrong expiration date format. Created an issue in Starcounter: https://github.com/Starcounter/Starcounter/issues/3847
2. Session cookie treats local time zone as UTC.
3. "Remember me" always remembers, even if it is unchecked.

Investigating.

**Comment by warpech** [comment]
1. Should be fixed after the next nightly build
2. Fixed in https://github.com/StarcounterPrefabs/SignIn/commit/3ada71718c585b247d60dd92542540d098732f76
3. Fixed in the same commit

**Comment by warpech** [comment]
Fixed on `develop` branch

**Comment by Mnosek** [comment]
I've tried it with latest pnext and it still doesn't work, cookie is Session expired. Do I need to do anything else?

**Comment by warpech** [comment]
You shouldn't have to. Let's investigate on your PC later today.

**Comment by warpech** [comment]
I thought I have tested it, but actually I made a dumb error. Fixed in d0de9b20b5f47b809f4d1261fa04d88dcd316c87

Can you please retest?

**Comment by warpech** [comment]
Please note that another issue still exists: https://github.com/StarcounterPrefabs/SignIn/issues/44

**Comment by Mnosek** [comment]
Works great, thanks a lot!
